/// Flutter icons AppIcoons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  AppIcoons
///      fonts:
///       - asset: fonts/AppIcoons.ttf
///
///
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
///
import 'package:flutter/widgets.dart';

class AppIcoons {
  AppIcoons._();

  static const _kFontFam = 'AppIcoons';
  static const String _kFontPkg = null;

  // static const IconData contratomediacao =
  //     IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  // static const IconData people =
  //     IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  // static const IconData dashboard =
  //     IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  // static const IconData escrituras =
  //     IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  // static const IconData faturacao =
  //     IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  // static const IconData objetivo =
  //     IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  // static const IconData promecacompravenda =
  //     IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  // static const IconData proposta =
  //     IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  // static const IconData tempoprospecao =
  //     IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  // static const IconData vendas =
  //     IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  // static const IconData angariacao =
  //     IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  // static const IconData apresentacaoservico =
  //     IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData contratomediacao =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData people =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dashboard =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plus =
      IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData escrituras =
      IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData faturacao =
      IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData objetivo =
      IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData promecacompravenda =
      IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData proposta =
      IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tempoprospecao =
      IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vendas =
      IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData angariacao =
      IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData apresentacaoservico =
      IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData save =
      IconData(0xf0c7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
